#!/bin/bash

# shellcheck disable=SC2034
INSTALL_LIST_PACKETS_TOINSTALL='hyprland
hyprlock
hyprpaper
waybar
kitty
dolphin
flatpak
firefox
nwg-dock-hyprland
SwayNotificationCenter
rofi
wlogout
fastfetch
flameshot
brave-browser
material-icons-fonts
fira-code-fonts
jetbrains-mono-fonts
mozilla-fira*
bibata-cursor-themes
fish
oh-my-posh'

INSTALL_LIST_PACKETS_TOINSTALL_OPTIONAL='xdotool[xdotool][dnf] Betterbird[eu.betterbird.Betterbird][flatpak]'

INSTALL_LIST_REPOS_TOINSTALL='solopasha/hyprland
erikreider/SwayNotificationCenter
tofik/nwg-shell
wef/cliphist
peterwu/rendezvous'